### ISSUE TITLE
Support for connect_server_msg_received_total/connect_server_msg_sent_total

### ISSUE THREAD

**Issue by pqn** [easyCZ/connect-go-prometheus#1]
Thanks for the library! Really useful for my team transitioning away from pure gRPC/[go-grpc-prometheus](https://github.com/grpc-ecosystem/go-grpc-prometheus). I was wondering if you were planning on implementing the [streams metrics](https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/82c243799c991a7d5859215fba44a81834a52a71/server_metrics.go#L40-L49) as well.

**Comment by easyCZ** [comment]
Hey @pqn,

Thanks for the feedback. I'll try to get to these over the break that's coming up. If you'd like to contribute, I'm also happy to accept PRs!
